site_name: Svelte Mini Projects
nav:
  - Start Here: resources.md
  - Multiplication Tables: 1-multiplication-tables.md
  - Color Picker: 2-color-picker.md
  - Move Pixel: 3-move-pixel.md
  - Actions: 3-actions.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python', 'swift']
extra_css:
  - css/style.css
